name: hello-world

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  my-job-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        node-version: [22.3.0]
    
    env:
      MODE: "dev"
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          
      - name: Install Playwright and Dependencies
        run: |
          npm ci
          npx playwright install --with-deps
          
      - name: Run Playwright Tests
        run: npx playwright test
      
      - name: Upload Playwright Report
        if: always() # Ensure this step runs regardless of previous steps' results
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: ./playwright-report/
          retention-days: 30

      - name: Trigger Cypress Workflow
        if: always() # Ensure this step runs regardless of previous steps' results
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.MY_SECRET_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"event_type": "run-cypress-tests"}' \
            https://api.github.com/repos/0909463521/GithubAction_Cypress/dispatches
