name: hello-world

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  my-job-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
        
    strategy:
      matrix:
        node-version: [22.3.0]
    
    env:
      MODE: "dev"
    
    steps:
      - uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{matrix.node-version}}
          
      # - name: Install Library
      #   run: |
      #     npm ci
      #     npx playwright install --with-deps
          
      # - name: Test Web App
      #   run: npx playwright test
      
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: ./playwright-report/
          retention-days: 30

      - name: Trigger Cypress Workflow
        if: always() # Ensure this step runs regardless of previous steps' results
        run: |
          curl -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: token ${{ secrets.MY_SECRET_TOKEN }}" \
            -H "Content-Type: application/json" \
            -d '{"ref": "main"}' \
            https://api.github.com/repos/0909463521/GithubAction_Cypress/dispatches