name: Upload Data

on:
  push:
    branches:
      - main

jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Generate Data
      run: echo "DATA=Hello from Repo A" > data.txt

    - name: Upload to GitHub Releases
      uses: actions/upload-artifact@v3
      with:
        name: data
        path: data.txt
